PicCode_Web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('steg.urls')),
]

steg/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', views.home, name='PicCode-home'),
    path('decode/', views.decode, name='PicCode-decode'),
    path('encode/', views.encode, name='PicCode-encode'),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

steg/models.py
from django.db import models
from django.utils import timezone
import os
from uuid import uuid4

def path_and_rename(instance, filename):
    upload_to = 'images'
    ext = filename.split('.')[-1]
    # get filename
    filename = '{}.{}'.format(uuid4().hex, ext)
    # return the whole path to the file
    return os.path.join(upload_to, filename)


# Create your models here.
class PicModel(models.Model):
	img = models.ImageField(upload_to = path_and_rename)

steg/forms.py
from django import forms


class UserDataForm(forms.Form):
	text_data=forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))
	file_data=forms.ImageField()
	password=forms.CharField()



class UserDecodeForm(forms.Form):
	file_data=forms.ImageField()
	password=forms.CharField()

steg/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import UserDataForm, UserDecodeForm
from .models import PicModel
from .encode import Encode_Image
from .decode import Decode_Image
from django.conf import settings



# Create your views here.
def home(request):
	#print(request)
	return render(request, 'steg/home.html')



def decode(request):
	#print(request)
	context={}
	context['title']='Decode'
	if (request.method=='POST'):
		form=UserDecodeForm(request.POST, request.FILES)
		if form.is_valid():
			di=Decode_Image()
			image=form.cleaned_data['file_data']
			psswd=form.cleaned_data['password']
			obj=PicModel.objects.create(img=image)
			obj.save()
			#location=(settings.MEDIA_ROOT+"\\"+(obj.img.name).replace('/','\\')) #for Windows OS
			location=(settings.MEDIA_ROOT+"/"+(obj.img.name)) #for Linux OS
			di.stegano_decode(location,psswd)
			if di.error_decode[0]==-1:
				context['error']=di.error_decode[1]
			else:
				context['text']=di.decode_text
		else:
			context['error']="form not valid"
			form=UserDecodeForm()
	else:
		form=UserDecodeForm()
	context['forms']=form
	context['fixed']='1'
	return render(request, 'steg/decode.html',context)



def encode(request):
	#print(request)
	context={}
	context['title']='Encode'
	if (request.method == 'POST'):
		form=UserDataForm(request.POST, request.FILES)
		if form.is_valid():
			ei=Encode_Image()
			text = form.cleaned_data['text_data']
			image = form.cleaned_data['file_data']
			psswd=form.cleaned_data['password']
			obj=PicModel.objects.create(img=image)
			obj.save()
			#location=((settings.MEDIA_ROOT+"\\"+(obj.img.name).replace('/','\\')))
			location=(settings.MEDIA_ROOT+"/"+(obj.img.name)) #for Linux OS
			ei.stegano_encode(text,psswd,location)
			if ei.error_encode[0]==-1:
				context['error']=ei.error_encode[1]
			else:
				context['image']=obj.img.url
			
		else:
			context['error']="form not valid"
			form=UserDataForm()
	else:
		form=UserDataForm()
	context['forms']=form
	return render(request, 'steg/encode.html',context)



steg/templates/steg/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% if title %}
          <title>PicCode - {{ title }}</title>
        {% else %}
          <title>PicCode</title>
        {% endif %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'steg/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'steg/base.css' %}" rel="stylesheet" />
    </head>
    <body onload="myFunction()">
        <div id="loading"></div>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="/"><div class="piccode_logo_text">PicCode</div></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/"><div class="piccode_navitem">Home</div></a></li>
                        <li class="nav-item"><a class="nav-link" href="/encode/"><div class="piccode_navitem">Encode</div></a></li>
                        <li class="nav-item"><a class="nav-link" href="/decode/"><div class="piccode_navitem">Decode</div></a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}{% endblock %}
        <!-- Footer-->
        {% if fixed %}
        <footer class="position-fixed py-5 bg-transparent ">
        {% else %}
        <footer class="position-static py-5 bg-transparent ">
        {% endif %}
            <div class="container px-5">
                <!-- <div class="row">
                    <div class="col">Hello</div>
                    <div class="col"><p class="text-left">World</p></div>
                </div> -->
                <div class="row">
                    <p class=" col text-center text-white">Created by <a href="https://github.com/Ant-Ghost/">Aunomitra Ghosh</a></p>
                    <p class=" col text-center text-white">Background vector created by starline -<a href='https://www.freepik.com/vectors/background'> www.freepik.com</a></p>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script type="text/javascript" src="{% static 'steg/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        <script type="text/javascript">
            var preloader=document.getElementById('loading');

            function myFunction() {
                console.log(preloader);
                preloader.style.display='none';
            }
        </script>
    </body>
</html>

steg/templates/steg/decode.html
{% extends "steg/base.html" %}
{% block content %}
	<section class="py-0 border-bottom" id="features" style="padding-bottom: 100px;">
            <div class="container px-5 my-5">
                <div class="row gx-5">
                    <div class="col-lg-4 mb-5 mb-lg-0">
						<form enctype="multipart/form-data" method="POST" action="">
							{% csrf_token %}
							<fieldset class="form-group bg-transparent" style="color:gold; font-weight: 250%;">
								<legend class="border-bottom mb-4" style="color:gold; font-weight: 300%;">Encoded Pic</legend>
								<div class="container" style="padding-top: 5px">
									<label>Select Picture: </label>
									{{ forms.file_data }}
								</div>
								<div class="container" style="padding-top: 10px">
									<label>Enter Your Password: </label>
									{{ forms.password }}
								</div>
								<div class="container" style="padding-top: 50px">
									<div class="form-group">
										<button class="btn btn-warning" type="submit">Decode</button>
									</div>
								</div>
							</fieldset> 
						</form>                       
                    </div>
                    <div class="col-lg-4 mx-auto text-center piccode_encode_center_sysmbol" style="padding-top: 100px; padding-bottom: 80px;">
                        <div class="feature bg-warning bg-gradient text-dark rounded-3 mb-3"><i class="bi bi-arrow-left-right"></i></div>
                    </div>
                    <div class="col-lg-4">
                        <form>
							{% csrf_token %}
							<fieldset class="form-group bg-transparent" style="color:gold; font-weight: 250%;">
								<legend class="border-bottom mb-4" style="color:gold; font-weight: 300%;">Message inside your Pic</legend>
								<div class="container">
									<label>Decoded Message: </label>
									<textarea name="text_data" cols="40" rows="10" required id="id_text_data" readonly>{{ text }}</textarea>
								</div>
							</fieldset> 
						</form>
                    </div>
                </div>
            </div>
        </section>
        {% if error %}
        <script type="text/javascript">
        	alert('{{ error }}');
        </script>
        {% endif %}
{% endblock content %}

steg/templates/steg/encode.html
{% extends "steg/base.html" %}
{% block content %}
	<section class="py-0 border-bottom" id="features" style="padding-bottom: 100px;">
            <div class="container px-5 my-5">
                <div class="row gx-5">
                    <div class="col-lg-4 mb-5 mb-lg-0">
						<form enctype="multipart/form-data" method="POST" action="">
							{% csrf_token %}
							<fieldset class="form-group bg-transparent" style="color:gold; font-weight: 250%;">
								<legend class="border-bottom mb-4" style="color:gold; font-weight: 300%;">Private Message</legend>
								<div class="container">
									<label>Private text: </label>
									{{ forms.text_data }}
								</div>
								<div class="container" style="padding-top: 5px">
									<label>Select Picture: </label>
									{{ forms.file_data }}
								</div>
								<div class="container" style="padding-top: 10px">
									<label>Enter Your Password: </label>
									{{ forms.password }}
								</div>
								<div class="container" style="padding-top: 50px">
									<div class="form-group">
										<button class="btn btn-warning" type="submit">Encode</button>
									</div>
								</div>
							</fieldset> 
						</form>                       
                    </div>
                    <div class="col-lg-4 mx-auto text-center piccode_encode_center_sysmbol" style="padding-top: 100px; padding-bottom: 80px;">
                        <div class="feature bg-warning bg-gradient text-dark rounded-3 mb-3"><i class="bi bi-arrow-left-right"></i></div>
                    </div>
                    <div class="col-lg-4">
                        <form>
							{% csrf_token %}
							<fieldset class="form-group bg-transparent" style="color:gold; font-weight: 250%;">
								<legend class="border-bottom mb-4" style="color:gold; font-weight: 300%;">Your Picture With Your Encoded Message</legend>
								{% if image %}
									<div class="container">
										<label>EnCoded Pic: </label>
										<a href="{{image}}"  download style="color:gold">Click to download</a>
									</div>
									<div class="container" style="padding-top: 10px;">
										<label style="font-weight: 400%;">Remember: </label>
										<p style="font-weight: 350%;">Please remember your password, you cannot see your message without your password.</p>
									</div>
								{% endif %}
							</fieldset> 
						</form>
                    </div>
                </div>
            </div>
        </section>
        {% if error %}
        <script type="text/javascript">
        	alert('{{ error }}');
        </script>
        {% endif %}
{% endblock content %}

steg/templates/steg/home.html
{% extends "steg/base.html" %}
{% block content %}
<!-- Header-->
        <header class="bg-transparent py-5">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            <h1 class="display-5 fw-bolder text-white mb-2">PicCode</h1>
                            <h4 class=" text-white mb-4">Hide your private text inside an innocent picture.</h4>
                            <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                                <a class="btn btn-warning btn-lg px-4 me-sm-3" href="/encode/">Encode</a>
                                <a class="btn btn-outline-warning btn-lg px-4" href="/decode/">Decode</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Features section-->
        <section class="py-5 border-bottom" id="features">
            <div class="container px-5 my-5">
                <div class="row gx-5">
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="feature bg-warning bg-gradient text-dark rounded-3 mb-3"><i class="bi bi-collection"></i></div>
                        <h2 class="h4 fw-bolder text-white">Steganogrphy</h2>
                        <p class="text-white">Steganography is the practice of concealing a message within another message or a physical object. In computing/electronic contexts, a computer file, message, image, or video is concealed within another file, message, image, or video.</p>
                        <a class="text-decoration-none"  style="color:gold;" href="https://en.wikipedia.org/wiki/Steganography">
                            Wikipedia
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="feature bg-warning bg-gradient text-dark rounded-3 mb-3"><i class="bi bi-box-arrow-in-down"></i></div>
                        <h2 class="h4 fw-bolder text-white">Encryption</h2>
                        <p class="text-white">I have implemented 256-bit AES to encrypt your data using your password. That particular data can be decrypted only by your password.</p>
                        <a class="text-decoration-none"  style="color:gold;" href="https://en.wikipedia.org/wiki/Advanced_Encryption_Standard">
                            AES Encryption
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                    <div class="col-lg-4">
                        <div class="feature bg-warning bg-gradient text-dark rounded-3 mb-3"><i class="bi bi-box-arrow-down"></i></div>
                        <h2 class="h4 fw-bolder text-white">The LSB Method</h2>
                        <p class="text-white">For each pixel, color is coded with three bytes: red, green and blue respectively. Each byte indicates the intensity of the corresponding color, and the range is from 0 to 255. It takes a byte corresponding to one of the three colors of a pixel, for example 01010110. The idea is to replace these low order bits of information by those that one wishes to conceal. If the message is successfully hidden in well-chosen then image the naked eye cannot perceive the difference.</p>
                        <a class="text-decoration-none" style="color:gold;" href="/encode/">
                            Encode page
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </section>
{% endblock content %}